spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  task:
    scheduling:
      pool:
        size: 5
server:
  port: 9999
#  use-forward-headers: true
#  forward-headers-strategy: framework
openai:
  model: ${OPENAI_MODEL:gpt-3.5-turbo}
  apiKey: ${OPENAI_API_KEY:}
zsxq:
  cookie: ${ZSXQ_COOKIE:你的星球cookie}
  groupId: ${ZSXQ_GROUP_ID:你的星球id}
  silenced: ${ZSXQ_SILENCED :true}
scheduler:
  list:
#    - name: chatbotTask
#      platform: zsxq
#      answer: openai
#      cron: '0/30 * * * * ?'
#    - name: demoTask
#      platform: demo
#      answer: demo
#      cron: '0/10 * * * * ?'